services:
  ups-monitor:
    build: .
    image: ups-monitor:latest
    container_name: ups-monitor
    environment:
      - UPS_HOST=ups@192.168.0.3
      - TIMEZONE=Europe/Paris
    ports:
      - "5010:5010"
    restart: unless-stopped
    volumes:
      - ./data:/app/data